// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  apiKey: "AIzaSyDwa8h5IVnSrluNi5kdZ89Goyu6yyDXPCU",
  authDomain: "jocy-cc5e6.firebaseapp.com",
  projectId: "jocy-cc5e6",
  storageBucket: "jocy-cc5e6.appspot.com",
  messagingSenderId: "334990595684",
  appId: "1:334990595684:web:89a58b00a3105c38cf3171",
  measurementId: "G-7PFJLFPCQL"
};
